POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
    "username": "username",
    "password": "pass"
}

###

POST http://localhost:3000/auth/sign-up
Content-Type: application/json

{
    "username": "username",
    "password": "pass"
}
